# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUszsl_gus_X0KyjhcLt1s4DnrCPvtHI
"""

tugas = [
    {"nama": "Belajar Python", "status": "belum"},
    {"nama": "olahraga", "status": "belum"},
    {"nama": "Bersepeda", "status": "belum"}
]


def tambah_tugas(daftar_tugas):
    tugas_baru = input("Masukan tugas baru = ")
    daftar_tugas.append({
        "nama": tugas_baru,
        "status": "belum"
    })


def lihat_tugas(daftar_tugas):
    nomor = 1

    for item in daftar_tugas:
        print(f"{nomor}, {item['nama']}, {item['status']}")
        nomor = nomor + 1


def hapus_tugas(daftar_tugas):
    lihat_tugas(daftar_tugas)

    try:
        nomor = int(input("Nomor yang mau dihapus = "))
    except:
        print("Harap masukan angka!")
        return

    index = nomor - 1

    if nomor >= 1 and nomor <= len(daftar_tugas):
        daftar_tugas.pop(index)
        print("Tugas berhasil dihapus")
    else:
        print("Tugas tidak valid")


def selesaikan_tugas(daftar_tugas):
    try:
        nomor = int(input("Nomor tugas yang selesai = "))
    except:
        print("Harap masukan angka!")
        return

    index = nomor - 1

    if nomor >= 1 and nomor <= len(daftar_tugas):
        daftar_tugas[index]["status"] = "selesai"
        print("Tugas selesai")
    else:
        print("Nomor tidak valid")


while True:
    print("Manajemen Tugas")
    print("1. Tambah Tugas")
    print("2. Lihat Tugas")
    print("3. Hapus Tugas")
    print("4. Selesaikan Tugas")
    print("5. Keluar")

    try:
        pilihan = int(input("Pilih Nomor = "))

        if pilihan == 1:
            tambah_tugas(tugas)

        elif pilihan == 2:
            lihat_tugas(tugas)

        elif pilihan == 3:
            hapus_tugas(tugas)

        elif pilihan == 4:
            selesaikan_tugas(tugas)

        elif pilihan == 5:
            break

        else:
            print("Pilihan tidak valid")

    except:
        print("Harap masukan angka")